name: Copy commit files

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.commits/**'

jobs:
  copy-commit-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Copy Files to Commits Directory
        run: |
          if [ ${{ github.actor }} != 'github-actions[bot]' ]; then
            echo ${{ github.actor }}
            if [ -d ".commits/" ]; then
              rm -r .commits/
            fi
            mkdir -p ".commits/${{ github.sha }}"
            cp -R "scripts/" ".commits/${{ github.sha }}/" 
            git add ".commits/${{ github.sha }}/"
          else
            exit 1
          fi

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.PAT }}
          message: "Add files from commit ${{ github.sha }} to .commits directory"
          branch: "main"
